name: Docs Build

on:
  push:
    branches-ignore:
    - 'dependabot/**'
  pull_request:

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

jobs:
  GitHub_Pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile
      BUNDLE_PATH: vendor/bundle
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Build
      run: |
        ./.github/scripts/docs.sh
